language: cpp
sudo: true

branches:
  only:
  - master

cache:
- directories:
  - $HOME/.cache

addons:
  apt:
    packages:
      - gdb

script:
  - export AWS_KVS_LOG_LEVEL=3
  - make -j
  - ulimit -c unlimited -S
  - timeout --signal=SIGABRT 60m ./bench/webrtc_client_benchmark
  - timeout --signal=SIGABRT 60m ./bench/webrtc_client_benchmark

after_failure:
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/tst/webrtc_client_test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

matrix:
  # MemorySanitizer and UndefinedBehaviorSanitizer are still WIP
  allow_failures:
    - env: allowTestFail=true

  include:
    # Code Coverage
    - name: "Linux GCC Code Coverage"
      os: linux
      compiler: gcc
      before_install:
        # TODO: Remove the following line. This is only a workaround for enabling IPv6, https://github.com/travis-ci/travis-ci/issues/8891.
        - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
      before_script:
        - mkdir build && cd build && cmake .. -DBUILD_BENCHMARK=TRUE
